spring:
  application:
    name: spring-security
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/ttm_fil_rouge?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update