package initiativedeuxsevres.ttm.model.enums;

public enum Fields {
    ACTIVITES_SERVICES_ADMINISTRATIFS_ET_SOUTIEN, ACTIVITES_SPECIALISEES_SCIENTIFIQUES_ET_TECHNIQUES,
    AGRICULTURE_SYLVICULTURE_PECHE, ARTS_SPECTACLES_ACTIVITES_RECREATIVES, COMMERCE_REPARATION, CONSTRUCTION_BTP,
    ENSEIGNEMENT, HOTELS_CAFES_RESTAURANTS, INDUSTRIE, INFORMATION_COMMUNICATION,
    PRODUCTION_DISTRIBUTION_EAU_ASSAINISSEMENT_GESTION_DECHETS_DEPOLLUTION, PRODUCTION_DISTRIBUTION_ELECTRICITE_GAZ_VAPEUR_AIR_CONDITIONNE,
    SANTE_HUMAINE_ACTION_SOCIALE, SERVICES_ENTREPRISES, SERVICES_PARTICULIERS, TRANSPORTS

}
